# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import audio_pb2 as audio__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AudioServiceStub(object):
    """Este bloque representa el nombre del servicio "AudioService"
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.downloadAudio = channel.unary_stream(
                '/AudioService/downloadAudio',
                request_serializer=audio__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=audio__pb2.DataChunkResponse.FromString,
                _registered_method=True)
        self.uploadAudio = channel.stream_unary(
                '/AudioService/uploadAudio',
                request_serializer=audio__pb2.DataChunkResponse.SerializeToString,
                response_deserializer=audio__pb2.DownloadFileRequest.FromString,
                _registered_method=True)


class AudioServiceServicer(object):
    """Este bloque representa el nombre del servicio "AudioService"
    """

    def downloadAudio(self, request, context):
        """Esta es la función para descargar archivos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uploadAudio(self, request_iterator, context):
        """Esta es la función para subir archivos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'downloadAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.downloadAudio,
                    request_deserializer=audio__pb2.DownloadFileRequest.FromString,
                    response_serializer=audio__pb2.DataChunkResponse.SerializeToString,
            ),
            'uploadAudio': grpc.stream_unary_rpc_method_handler(
                    servicer.uploadAudio,
                    request_deserializer=audio__pb2.DataChunkResponse.FromString,
                    response_serializer=audio__pb2.DownloadFileRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AudioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Este bloque representa el nombre del servicio "AudioService"
    """

    @staticmethod
    def downloadAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/AudioService/downloadAudio',
            audio__pb2.DownloadFileRequest.SerializeToString,
            audio__pb2.DataChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def uploadAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/AudioService/uploadAudio',
            audio__pb2.DataChunkResponse.SerializeToString,
            audio__pb2.DownloadFileRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
